[package]
name = "enchiridion_api"
version = "0.1.0"
authors = ["Steven Hansel <stevenhanselgo@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "enchiridion_api"

[dependencies]
actix-web = "4.0.1"
reqwest = "0.11.10"
tokio = { version = "1.19.0", features = ["macros", "rt-multi-thread"] }
