[package]
name = "enchiridion_api"
version = "0.1.0"
authors = ["Steven Hansel <stevenhanselgo@gmail.com>"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "enchiridion_api"

[dependencies]
actix-web = "4.0.1"
sqlx = { version = "0.5", features = [ "runtime-tokio-native-tls" , "postgres" ] }
reqwest = "0.11.10"
tokio = { version = "1.19.0", features = ["macros", "rt-multi-thread"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
futures = "0.3"
shaku = "0.6.1"
shaku_actix = "0.2.0"
async-trait = "0.1.56"
password-hash = { version = "0.4.1", features = ["alloc"] }
argon2 = "0.4"
rand_core = { version = "0.6", features = ["std"] }
secrecy = { version = "0.8.0", features = ["serde"] }
dotenv_codegen = "0.15.0"
dotenvy = "0.15.1"
validator = { version = "0.15.0", features = ["derive"] }
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.2"
chrono = "0.4.19"
